"""Declarative field plan for the FNMA ``loan_issuance`` combined master.

This is the committed, single-source-of-truth column map for fusing the two
Fannie loan-level spines:

  * base  = SF Loan-Performance issuances  ("MBS",  ``fnma/silver/issuances``)
  * enrich = FNM_ILLD UMBS pool-disclosure ("UMBS", ``umbs/silver/FNMA/ILLD``)
            UNION the first FNM_MLLD monthly snapshot (pre-2019-06 recovery, D-6)

bridged by the strictly-1:1 ``crosswalk/mbs_umbs/fnma_crosswalk.parquet``.

Each entry maps one unified output field to its source column(s):

  name         unified output column name
  sf           list of SF source columns (vintage aliases OR-ed via coalesce)
  il           list of ILLD source columns (vintage aliases OR-ed via coalesce)
  disposition  one of:
                 key           handled explicitly by the builder
                 sf_only       pass through from SF
                 umbs_only     pass through from ILLD
                 shared_keep   in both, agree >=99.8% -> coalesce(SF, ILLD)
                 shared_harmon in both, code/encoding differs -> bespoke transform
                 shared_both   keep both copies (participation-weighted vs full)
                 drop          filler / empty -> not carried

The harmonization decisions (D-1..D-6) are documented in
``investigations/reports/investigation_fnma_mbs_umbs_combine_2026-06-18.md`` and
``docs/design/combined_spec.md``. The plan itself is generated from the validated
column table (``investigation_fnma_mbs_umbs_combine_table_2026-06-18.py``); every
SF and ILLD source column is asserted accounted for there.
"""

from __future__ import annotations

from typing import Final, TypedDict


class FieldSpec(TypedDict):
    """One unified output field and the source column(s) it draws on."""

    name: str
    sf: list[str]
    il: list[str]
    disposition: str


#: The three primary loan dates parsed to ``pl.Date`` (first-of-month), per D-2.
DATE_FIELDS: Final[frozenset[str]] = frozenset(
    {"first_payment_date", "maturity_date", "origination_date"}
)

#: Fields coalesced ILLD-first because ILLD is the higher-fidelity source.
#: - ``mi_percent`` (D-4): ILLD is 100%-populated with explicit 0 = "no MI"; SF is null
#:   when there is no MI.
#: - ``seller_name`` / ``servicer_name`` / ``mi_cancellation_ind``: the SF disclosure
#:   VALUE-MASKS small entities as "Other" (only ~50-80 distinct sellers/servicers) while
#:   ILLD discloses the real names (~1,200-1,550) and rescues 100% of the masked rows
#:   (``investigation_sf_umbs_source_fidelity_2026-06-26``). ILLD-first recovers the true
#:   names for 2019-06+ loans; pre-2019 history falls back to the (masked) SF value.
IL_FIRST_FIELDS: Final[frozenset[str]] = frozenset(
    {"mi_percent", "seller_name", "servicer_name", "mi_cancellation_ind"}
)

FNMA_LOAN_ISSUANCE_PLAN: Final[list[FieldSpec]] = [
    {"name": "loan_key_sf", "sf": ["Loan Identifier"], "il": [], "disposition": "key"},
    {"name": "loan_key_umbs", "sf": [], "il": ["Loan Identifier"], "disposition": "key"},
    {"name": "has_umbs_match", "sf": [], "il": [], "disposition": "key"},
    {
        "name": "umbs_correction_ind",
        "sf": [],
        "il": ["Loan Correction Indicator"],
        "disposition": "umbs_only",
    },
    {"name": "umbs_source_record", "sf": [], "il": ["_record_source"], "disposition": "umbs_only"},
    {
        "name": "sf_reporting_period",
        "sf": ["Monthly Reporting Period"],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "sf_silver_is_issuance", "sf": ["is_issuance"], "il": [], "disposition": "drop"},
    {"name": "sf_silver_is_termination", "sf": ["is_termination"], "il": [], "disposition": "drop"},
    {"name": "cusip", "sf": [], "il": ["CUSIP"], "disposition": "umbs_only"},
    {"name": "security_id", "sf": [], "il": ["Security Identifier"], "disposition": "umbs_only"},
    {"name": "pool_prefix", "sf": [], "il": ["Prefix"], "disposition": "umbs_only"},
    {"name": "reference_pool_id", "sf": ["Reference Pool ID"], "il": [], "disposition": "sf_only"},
    {
        "name": "loan_participation_pct",
        "sf": [],
        "il": ["Loan Participation Percent"],
        "disposition": "umbs_only",
    },
    {"name": "deal_name", "sf": ["Deal Name"], "il": [], "disposition": "sf_only"},
    {
        "name": "seller_name",
        "sf": ["Seller Name"],
        "il": ["Seller Name"],
        "disposition": "shared_keep",
    },
    {
        "name": "servicer_name",
        "sf": ["Servicer Name"],
        "il": ["Servicer Name"],
        "disposition": "shared_keep",
    },
    {"name": "master_servicer", "sf": ["Master Servicer"], "il": [], "disposition": "sf_only"},
    {"name": "seller_city", "sf": [], "il": ["Seller City"], "disposition": "umbs_only"},
    {"name": "seller_state", "sf": [], "il": ["Seller State"], "disposition": "umbs_only"},
    {"name": "servicer_city", "sf": [], "il": ["Servicer City"], "disposition": "umbs_only"},
    {"name": "servicer_state", "sf": [], "il": ["Servicer State"], "disposition": "umbs_only"},
    {
        "name": "original_upb",
        "sf": ["Original UPB"],
        "il": ["Mortgage Loan Amount"],
        "disposition": "shared_keep",
    },
    {
        "name": "issuance_investor_upb",
        "sf": ["UPB at Issuance"],
        "il": ["Issuance Investor Loan UPB"],
        "disposition": "shared_both",
    },
    {
        "name": "current_actual_upb",
        "sf": ["Current Actual UPB"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "current_investor_upb",
        "sf": [],
        "il": ["Current Investor Loan UPB"],
        "disposition": "umbs_only",
    },
    {
        "name": "interest_bearing_upb",
        "sf": ["Interest Bearing UPB"],
        "il": ["Interest Bearing Mortgage Loan Amount"],
        "disposition": "shared_keep",
    },
    {
        "name": "note_rate",
        "sf": ["Original Interest Rate"],
        "il": ["Original Interest Rate"],
        "disposition": "shared_keep",
    },
    {
        "name": "issuance_rate",
        "sf": [],
        "il": ["Issuance Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "net_rate",
        "sf": [],
        "il": ["Issuance Net Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "current_rate",
        "sf": ["Current Interest Rate"],
        "il": ["Current Interest Rate"],
        "disposition": "shared_keep",
    },
    {
        "name": "current_net_rate",
        "sf": [],
        "il": ["Current Net Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "loan_term",
        "sf": ["Original Loan Term"],
        "il": ["Loan Term"],
        "disposition": "shared_keep",
    },
    {"name": "loan_age", "sf": ["Loan Age"], "il": ["Loan Age"], "disposition": "shared_keep"},
    {
        "name": "remaining_months_to_maturity",
        "sf": ["Remaining Months To Maturity"],
        "il": ["Remaining Months to Maturity"],
        "disposition": "shared_keep",
    },
    {
        "name": "remaining_months_legal_maturity",
        "sf": ["Remaining Months to Legal Maturity"],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "origination_date", "sf": ["Origination Date"], "il": [], "disposition": "sf_only"},
    {
        "name": "first_payment_date",
        "sf": ["First Payment Date"],
        "il": ["First Payment Date"],
        "disposition": "shared_harmon",
    },
    {
        "name": "maturity_date",
        "sf": ["Maturity Date"],
        "il": ["Maturity Date"],
        "disposition": "shared_harmon",
    },
    {
        "name": "next_rate_adjustment_date",
        "sf": ["Next Interest Rate Adjustment Date"],
        "il": ["Next Interest Rate Adjustment Date"],
        "disposition": "shared_keep",
    },
    {
        "name": "next_payment_change_date",
        "sf": ["Next Payment Change Date"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "months_to_next_rate_adjustment",
        "sf": [],
        "il": ["Months to Next Interest Rate Adjustment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "ltv",
        "sf": ["Original Loan to Value Ratio (LTV)"],
        "il": ["Loan-To-Value (LTV)"],
        "disposition": "shared_keep",
    },
    {
        "name": "cltv",
        "sf": ["Original Combined Loan to Value Ratio (CLTV)"],
        "il": ["Combined Loan-To-Value (CLTV)"],
        "disposition": "shared_keep",
    },
    {
        "name": "dti",
        "sf": ["Debt-To-Income (DTI)"],
        "il": ["Debt-To-Income (DTI)"],
        "disposition": "shared_keep",
    },
    {
        "name": "estimated_ltv",
        "sf": [],
        "il": ["Estimated Loan-To-Value (ELTV)"],
        "disposition": "umbs_only",
    },
    {
        "name": "high_balance_ind",
        "sf": ["High Balance Loan Indicator "],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "hltv_refi_option_ind",
        "sf": ["High Loan to Value (HLTV) Refinance Option Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "borrower_credit_score",
        "sf": ["Borrower Credit Score at Origination", "Origination Classic FICO®"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "co_borrower_credit_score",
        "sf": ["Co-Borrower Credit Score at Origination"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "representative_credit_score",
        "sf": [],
        "il": ["Borrower Credit Score", "Classic FICO", "Origination Classic FICO"],
        "disposition": "shared_harmon",
    },
    {
        "name": "credit_score_issuance",
        "sf": ["Borrower Credit Score At Issuance", "Issuance Classic FICO®"],
        "il": [],
        "disposition": "drop",
    },
    {
        "name": "credit_score_current",
        "sf": ["Current Classic FICO®", "Borrower Credit Score Current "],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "co_borrower_credit_score_issuance",
        "sf": ["Co-Borrower Credit Score At Issuance"],
        "il": [],
        "disposition": "drop",
    },
    {
        "name": "co_borrower_credit_score_current",
        "sf": ["Co-Borrower Credit Score Current"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "updated_credit_score",
        "sf": [],
        "il": ["Updated Credit Score", "Updated Classic FICO"],
        "disposition": "umbs_only",
    },
    {"name": "vs4_score", "sf": [], "il": ["VS4", "Origination VS4"], "disposition": "umbs_only"},
    {"name": "vs4_updated", "sf": [], "il": ["Updated VS4"], "disposition": "umbs_only"},
    {
        "name": "number_of_borrowers",
        "sf": ["Number of Borrowers"],
        "il": ["Number of Borrowers"],
        "disposition": "shared_keep",
    },
    {
        "name": "number_of_units",
        "sf": ["Number of Units"],
        "il": ["Number of Units"],
        "disposition": "shared_keep",
    },
    {
        "name": "first_time_homebuyer",
        "sf": ["First Time Home Buyer Indicator"],
        "il": ["First Time Home Buyer Indicator"],
        "disposition": "shared_keep",
    },
    {
        "name": "loan_purpose",
        "sf": ["Loan Purpose "],
        "il": ["Loan Purpose"],
        "disposition": "shared_harmon",
    },
    {
        "name": "occupancy",
        "sf": ["Occupancy Status"],
        "il": ["Occupancy Status"],
        "disposition": "shared_keep",
    },
    {
        "name": "property_type",
        "sf": ["Property Type"],
        "il": ["Property Type"],
        "disposition": "shared_keep",
    },
    {"name": "channel", "sf": ["Channel"], "il": ["Channel"], "disposition": "shared_keep"},
    {
        "name": "amortization_type",
        "sf": ["Amortization Type"],
        "il": ["Amortization Type"],
        "disposition": "shared_keep",
    },
    {
        "name": "property_state",
        "sf": ["Property State"],
        "il": ["Property State"],
        "disposition": "shared_keep",
    },
    {
        "name": "property_valuation_method",
        "sf": ["Property Valuation Method "],
        "il": ["Property Valuation Method"],
        "disposition": "shared_keep",
    },
    {
        "name": "relocation_mortgage_ind",
        "sf": ["Relocation Mortgage Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "negative_amortization_ind",
        "sf": ["Negative Amortization Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "non_standard_documentation_ind",
        "sf": ["Non-Standard Documentation Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "non_standard_underwriting_ind",
        "sf": ["Non-Standard Underwriting or Eligibility Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "msa",
        "sf": [
            "Metropolitan Statistical Area (MSA) or Metropolitan Statistical Division Area (MSDA)",
            "Metropolitan Statistical Area (MSA)",
        ],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "zip3", "sf": ["Zip Code Short"], "il": [], "disposition": "sf_only"},
    {
        "name": "mi_percent",
        "sf": ["Mortgage Insurance Percentage"],
        "il": ["Mortgage Insurance Percent"],
        "disposition": "shared_harmon",
    },
    {
        "name": "mi_cancellation_ind",
        "sf": ["Mortgage Insurance Cancellation Indicator"],
        "il": ["Mortgage Insurance Cancellation Indicator"],
        "disposition": "shared_keep",
    },
    {"name": "mi_type", "sf": ["Mortgage Insurance Type"], "il": [], "disposition": "sf_only"},
    {
        "name": "government_insured_guarantee",
        "sf": ["Government Insured/Guarantee Indicator"],
        "il": ["Government Insured Guarantee"],
        "disposition": "shared_keep",
    },
    {
        "name": "interest_only_ind",
        "sf": ["Interest Only Loan Indicator"],
        "il": ["Interest Only Loan Indicator"],
        "disposition": "shared_keep",
    },
    {
        "name": "io_first_pi_date",
        "sf": ["Interest Only First Principal And Interest Payment Date"],
        "il": ["Interest Only First Principal and Interest Payment Date"],
        "disposition": "shared_keep",
    },
    {
        "name": "months_to_amortization",
        "sf": ["Months to Amortization"],
        "il": ["Months to Amortization"],
        "disposition": "shared_keep",
    },
    {
        "name": "prepayment_penalty_ind",
        "sf": ["Prepayment Penalty Indicator"],
        "il": ["Prepayment Penalty Indicator"],
        "disposition": "shared_keep",
    },
    {
        "name": "prepayment_penalty_term",
        "sf": [],
        "il": ["Prepayment Penalty Total Term"],
        "disposition": "umbs_only",
    },
    {
        "name": "assumability_ind",
        "sf": [],
        "il": ["Assumability Indicator"],
        "disposition": "umbs_only",
    },
    {
        "name": "special_eligibility_program",
        "sf": ["Special Eligibility Program"],
        "il": ["Special Eligibility Program"],
        "disposition": "shared_keep",
    },
    {
        "name": "servicing_activity_ind",
        "sf": ["Servicing Activity Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "arm_index", "sf": ["Index"], "il": ["Index"], "disposition": "shared_keep"},
    {
        "name": "arm_margin",
        "sf": ["Mortgage Margin"],
        "il": ["Mortgage Margin"],
        "disposition": "shared_keep",
    },
    {"name": "arm_pc_margin", "sf": [], "il": ["MBS PC Margin"], "disposition": "umbs_only"},
    {
        "name": "arm_adj_frequency",
        "sf": ["Interest Rate Adjustment Frequency"],
        "il": ["Interest Rate Adjustment Frequency"],
        "disposition": "shared_keep",
    },
    {
        "name": "arm_initial_fixed_period",
        "sf": ["Initial Fixed-Rate Period "],
        "il": ["Initial Fixed Rate Period"],
        "disposition": "shared_keep",
    },
    {
        "name": "arm_init_cap_up",
        "sf": ["Initial Interest Rate Cap Up Percent"],
        "il": ["Initial Interest Rate Cap Up Percent"],
        "disposition": "shared_keep",
    },
    {
        "name": "arm_periodic_cap_up",
        "sf": ["Periodic Interest Rate Cap Up Percent"],
        "il": ["Periodic Interest Rate Cap Up Percent"],
        "disposition": "shared_keep",
    },
    {
        "name": "arm_life_cap_up",
        "sf": ["Lifetime Interest Rate Cap Up Percent"],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "arm_product_type", "sf": ["ARM Product Type"], "il": [], "disposition": "sf_only"},
    {"name": "arm_plan_number", "sf": ["ARM Plan Number"], "il": [], "disposition": "sf_only"},
    {"name": "arm_cap_structure", "sf": ["ARM Cap Structure"], "il": [], "disposition": "sf_only"},
    {
        "name": "arm_balloon_ind",
        "sf": ["ARM Balloon Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "arm_initial_fixed_le5yr_ind",
        "sf": ["ARM Initial Fixed-Rate Period  ≤ 5 YR Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "arm_init_cap_down",
        "sf": [],
        "il": ["Initial Interest Rate Cap Down Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_periodic_cap_down",
        "sf": [],
        "il": ["Periodic Interest Rate Cap Down Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_lookback",
        "sf": [],
        "il": ["Interest Rate Lookback"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_rounding_method",
        "sf": [],
        "il": ["Interest Rate Rounding Method"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_rounding_pct",
        "sf": [],
        "il": ["Interest Rate Rounding Method Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_convertibility",
        "sf": [],
        "il": ["Convertibility Indicator"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_life_ceiling",
        "sf": [],
        "il": ["Life Ceiling Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_life_ceiling_net",
        "sf": [],
        "il": ["Life Ceiling Net Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_life_floor",
        "sf": [],
        "il": ["Life Floor Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_life_floor_net",
        "sf": [],
        "il": ["Life Floor Net Interest Rate"],
        "disposition": "umbs_only",
    },
    {"name": "modification_flag", "sf": ["Modification Flag"], "il": [], "disposition": "sf_only"},
    {
        "name": "borrower_assistance_plan",
        "sf": ["Borrower Assistance Plan"],
        "il": ["Borrower Assistance Plan"],
        "disposition": "shared_keep",
    },
    {
        "name": "alternative_delinquency_resolution",
        "sf": ["Alternative Delinquency Resolution"],
        "il": ["Alternative Delinquency Resolution"],
        "disposition": "shared_keep",
    },
    {
        "name": "alternative_delinquency_resolution_count",
        "sf": ["Alternative Delinquency  Resolution Count"],
        "il": ["Number of Alternative Delinquency Resolutions"],
        "disposition": "shared_keep",
    },
    {
        "name": "total_deferral_amount",
        "sf": ["Total Deferral Amount "],
        "il": ["Total Deferral Amount"],
        "disposition": "shared_keep",
    },
    {
        "name": "payment_deferral_mod_event_ind",
        "sf": ["Payment Deferral Modification Event Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "umbs_modification_program",
        "sf": [],
        "il": ["Modification Program"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_modification_type",
        "sf": [],
        "il": ["Modification Type"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_number_of_modifications",
        "sf": [],
        "il": ["Number of Modifications"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_total_capitalized_amount",
        "sf": [],
        "il": ["Total Capitalized Amount"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_original_deferred_amount",
        "sf": [],
        "il": ["Original Deferred Amount"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_current_deferred_upb",
        "sf": [],
        "il": ["Current Deferred UPB"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_loan_age_as_of_mod",
        "sf": [],
        "il": ["Loan Age As Of Modification"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_indicator",
        "sf": [],
        "il": ["Interest Rate Step Indicator"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_initial_fixed_period",
        "sf": [],
        "il": ["Initial Step Fixed-Rate Period"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_total_steps",
        "sf": [],
        "il": ["Total Number of Steps"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_remaining_steps",
        "sf": [],
        "il": ["Number of Remaining Steps"],
        "disposition": "umbs_only",
    },
    {"name": "step_next_rate", "sf": [], "il": ["Next Step Rate"], "disposition": "umbs_only"},
    {
        "name": "step_terminal_rate",
        "sf": [],
        "il": ["Terminal Step Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_terminal_date",
        "sf": [],
        "il": ["Terminal Step Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_adj_frequency",
        "sf": [],
        "il": ["Step Rate Adjustment Frequency"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_next_adj_date",
        "sf": [],
        "il": ["Next Step Rate Adjustment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_months_to_next_adj",
        "sf": [],
        "il": ["Months to Next Step Rate Adjustment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_periodic_cap_up",
        "sf": [],
        "il": ["Periodic Step Cap Up Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_upb_restated",
        "sf": [],
        "il": ["Origination Mortgage Loan Amount"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_rate_restated",
        "sf": [],
        "il": ["Origination Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_amort_restated",
        "sf": [],
        "il": ["Origination Amortization Type"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_io_restated",
        "sf": [],
        "il": ["Origination Interest Only Loan Indicator"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_fpd_restated",
        "sf": [],
        "il": ["Origination First Payment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_maturity_restated",
        "sf": [],
        "il": ["Origination Maturity Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_term_restated",
        "sf": [],
        "il": ["Origination Loan Term"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_ltv_restated",
        "sf": [],
        "il": ["Origination Loan-To-Value (LTV)"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_cltv_restated",
        "sf": [],
        "il": ["Origination Combined Loan-To-Value (CLTV)"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_dti_restated",
        "sf": [],
        "il": ["Origination Debt-To-Income Ratio"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_credit_score_restated",
        "sf": [],
        "il": ["Origination Credit Score"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_purpose_restated",
        "sf": [],
        "il": ["Origination Loan Purpose"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_occupancy_restated",
        "sf": [],
        "il": ["Origination Occupancy Status"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_channel_restated",
        "sf": [],
        "il": ["Origination Channel"],
        "disposition": "umbs_only",
    },
    {
        "name": "delinquency_status",
        "sf": ["Current Loan Delinquency Status"],
        "il": ["Days Delinquent"],
        "disposition": "shared_harmon",
    },
    {
        "name": "loan_payment_history",
        "sf": ["Loan Payment History"],
        "il": ["Loan Performance History"],
        "disposition": "shared_harmon",
    },
    {
        "name": "delinquent_accrued_interest",
        "sf": ["Delinquent Accrued Interest"],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "zero_balance_code", "sf": ["Zero Balance Code"], "il": [], "disposition": "sf_only"},
    {
        "name": "zero_balance_effective_date",
        "sf": ["Zero Balance Effective Date"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "zero_balance_code_change_date",
        "sf": ["Zero Balance Code Change Date"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "upb_at_removal",
        "sf": ["UPB at the Time of Removal"],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "repurchase_date", "sf": ["Repurchase Date"], "il": [], "disposition": "sf_only"},
    {
        "name": "scheduled_principal_current",
        "sf": ["Scheduled Principal Current"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "total_principal_current",
        "sf": ["Total Principal Current"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "unscheduled_principal_current",
        "sf": ["Unscheduled Principal Current"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "last_paid_installment_date",
        "sf": ["Last Paid Installment Date"],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "foreclosure_date", "sf": ["Foreclosure Date"], "il": [], "disposition": "sf_only"},
    {"name": "disposition_date", "sf": ["Disposition Date"], "il": [], "disposition": "sf_only"},
    {"name": "foreclosure_costs", "sf": ["Foreclosure Costs"], "il": [], "disposition": "sf_only"},
    {
        "name": "property_preservation_costs",
        "sf": ["Property Preservation and Repair Costs"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "asset_recovery_costs",
        "sf": ["Asset Recovery Costs"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "misc_holding_expenses",
        "sf": ["Miscellaneous Holding Expenses and Credits"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "holding_taxes",
        "sf": ["Associated Taxes for Holding Property"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "net_sales_proceeds",
        "sf": ["Net Sales Proceeds"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "credit_enhancement_proceeds",
        "sf": ["Credit Enhancement Proceeds"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "repurchase_make_whole_proceeds",
        "sf": ["Repurchase Make Whole Proceeds"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "repurchase_make_whole_proceeds_flag",
        "sf": ["Repurchase Make Whole Proceeds Flag"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "other_foreclosure_proceeds",
        "sf": ["Other Foreclosure Proceeds"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "foreclosure_principal_writeoff",
        "sf": ["Foreclosure Principal Write-off Amount"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "mod_noninterest_bearing_upb",
        "sf": ["Modification-Related Non-Interest Bearing UPB"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "principal_forgiveness_amount",
        "sf": ["Principal Forgiveness Amount"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "original_list_start_date",
        "sf": ["Original List Start Date"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "original_list_price",
        "sf": ["Original List Price"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "current_list_start_date",
        "sf": ["Current List Start Date"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "current_list_price",
        "sf": ["Current List Price"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "current_period_mod_loss",
        "sf": ["Current Period Modification Loss Amount"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "cumulative_mod_loss",
        "sf": ["Cumulative Modification Loss Amount"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "current_period_credit_event_gainloss",
        "sf": ["Current Period Credit Event Net Gain or Loss"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "cumulative_credit_event_gainloss",
        "sf": ["Cumulative Credit Event Net Gain or Loss"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "loan_holdback_ind",
        "sf": ["Loan Holdback Indicator"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "loan_holdback_effective_date",
        "sf": ["Loan Holdback Effective Date"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "_filler",
        "sf": [],
        "il": [
            "Filler",
            "Filler_duplicated_0",
            "Filler_duplicated_1",
            "Filler_duplicated_2",
            "Filler_duplicated_3",
            "Filler_duplicated_4",
            "Filler_duplicated_5",
        ],
        "disposition": "drop",
    },
]


FHLMC_LOAN_ISSUANCE_PLAN: Final[list[FieldSpec]] = [
    {"name": "loan_key_sf", "sf": ["Loan Sequence Number"], "il": [], "disposition": "key"},
    {"name": "loan_key_umbs", "sf": [], "il": ["Loan Identifier"], "disposition": "key"},
    {"name": "has_umbs_match", "sf": [], "il": [], "disposition": "key"},
    {
        "name": "umbs_correction_ind",
        "sf": [],
        "il": ["Loan Correction Indicator"],
        "disposition": "umbs_only",
    },
    {"name": "umbs_source_record", "sf": [], "il": ["_record_source"], "disposition": "umbs_only"},
    {"name": "sf_silver_is_issuance", "sf": ["is_issuance"], "il": [], "disposition": "drop"},
    {"name": "sf_silver_is_termination", "sf": ["is_termination"], "il": [], "disposition": "drop"},
    {"name": "cusip", "sf": [], "il": ["CUSIP"], "disposition": "umbs_only"},
    {"name": "security_id", "sf": [], "il": ["Security Identifier"], "disposition": "umbs_only"},
    {"name": "pool_prefix", "sf": [], "il": ["Prefix"], "disposition": "umbs_only"},
    {
        "name": "loan_participation_pct",
        "sf": [],
        "il": ["Loan Participation Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "seller_name",
        "sf": ["Seller Name"],
        "il": ["Seller Name"],
        "disposition": "shared_keep",
    },
    {
        "name": "servicer_name",
        "sf": ["Servicer Name"],
        "il": ["Servicer Name"],
        "disposition": "shared_keep",
    },
    {"name": "seller_city", "sf": [], "il": ["Seller City"], "disposition": "umbs_only"},
    {"name": "seller_state", "sf": [], "il": ["Seller State"], "disposition": "umbs_only"},
    {"name": "servicer_city", "sf": [], "il": ["Servicer City"], "disposition": "umbs_only"},
    {"name": "servicer_state", "sf": [], "il": ["Servicer State"], "disposition": "umbs_only"},
    {
        "name": "original_upb",
        "sf": ["Original UPB"],
        "il": ["Mortgage Loan Amount"],
        "disposition": "shared_keep",
    },
    {
        "name": "issuance_investor_upb",
        "sf": [],
        "il": ["Issuance Investor Loan UPB"],
        "disposition": "umbs_only",
    },
    {
        "name": "current_investor_upb",
        "sf": [],
        "il": ["Current Investor Loan UPB"],
        "disposition": "umbs_only",
    },
    {
        "name": "interest_bearing_upb",
        "sf": [],
        "il": ["Interest Bearing Mortgage Loan Amount"],
        "disposition": "umbs_only",
    },
    {
        "name": "note_rate",
        "sf": ["Original Interest Rate"],
        "il": ["Original Interest Rate"],
        "disposition": "shared_keep",
    },
    {
        "name": "issuance_rate",
        "sf": [],
        "il": ["Issuance Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "net_rate",
        "sf": [],
        "il": ["Issuance Net Interest Rate"],
        "disposition": "umbs_only",
    },
    {"name": "current_rate", "sf": [], "il": ["Current Interest Rate"], "disposition": "umbs_only"},
    {
        "name": "current_net_rate",
        "sf": [],
        "il": ["Current Net Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "loan_term",
        "sf": ["Original Loan Term"],
        "il": ["Loan Term"],
        "disposition": "shared_keep",
    },
    {"name": "loan_age", "sf": [], "il": ["Loan Age"], "disposition": "umbs_only"},
    {
        "name": "remaining_months_to_maturity",
        "sf": [],
        "il": ["Remaining Months to Maturity"],
        "disposition": "umbs_only",
    },
    {
        "name": "first_payment_date",
        "sf": ["First Payment Date"],
        "il": ["First Payment Date"],
        "disposition": "shared_harmon",
    },
    {
        "name": "maturity_date",
        "sf": ["Maturity Date"],
        "il": ["Maturity Date"],
        "disposition": "shared_harmon",
    },
    {
        "name": "next_rate_adjustment_date",
        "sf": [],
        "il": ["Next Interest Rate Adjustment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "months_to_next_rate_adjustment",
        "sf": [],
        "il": ["Months to Next Interest Rate Adjustment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "ltv",
        "sf": ["Original Loan-to-Value (LTV)"],
        "il": ["Loan-To-Value (LTV)"],
        "disposition": "shared_keep",
    },
    {
        "name": "cltv",
        "sf": ["Original Combined Loan-to-Value (CLTV)"],
        "il": ["Combined Loan-To-Value (CLTV)"],
        "disposition": "shared_keep",
    },
    {
        "name": "dti",
        "sf": ["Original Debt-to-Income (DTI) Ratio"],
        "il": ["Debt-To-Income (DTI)"],
        "disposition": "shared_keep",
    },
    {
        "name": "estimated_ltv",
        "sf": [],
        "il": ["Estimated Loan-To-Value (ELTV)"],
        "disposition": "umbs_only",
    },
    {
        "name": "representative_credit_score",
        "sf": ["Credit Score"],
        "il": ["Borrower Credit Score", "Classic FICO", "Origination Classic FICO"],
        "disposition": "shared_keep",
    },
    {
        "name": "credit_score_issuance",
        "sf": ["Borrower Credit Score At Issuance", "Issuance Classic FICO®"],
        "il": [],
        "disposition": "drop",
    },
    {
        "name": "co_borrower_credit_score_issuance",
        "sf": ["Co-Borrower Credit Score At Issuance"],
        "il": [],
        "disposition": "drop",
    },
    {
        "name": "updated_credit_score",
        "sf": [],
        "il": ["Updated Credit Score", "Updated Classic FICO"],
        "disposition": "umbs_only",
    },
    {"name": "vs4_score", "sf": [], "il": ["VS4", "Origination VS4"], "disposition": "umbs_only"},
    {"name": "vs4_updated", "sf": [], "il": ["Updated VS4"], "disposition": "umbs_only"},
    {
        "name": "number_of_borrowers",
        "sf": ["Number of Borrowers"],
        "il": ["Number of Borrowers"],
        "disposition": "shared_keep",
    },
    {
        "name": "number_of_units",
        "sf": ["Number of Units"],
        "il": ["Number of Units"],
        "disposition": "shared_keep",
    },
    {
        "name": "first_time_homebuyer",
        "sf": ["First Time Homebuyer Flag"],
        "il": ["First Time Home Buyer Indicator"],
        "disposition": "shared_keep",
    },
    {
        "name": "loan_purpose",
        "sf": ["Loan Purpose"],
        "il": ["Loan Purpose"],
        "disposition": "shared_harmon",
    },
    {
        "name": "occupancy",
        "sf": ["Occupancy Status"],
        "il": ["Occupancy Status"],
        "disposition": "shared_keep",
    },
    {
        "name": "property_type",
        "sf": ["Property Type"],
        "il": ["Property Type"],
        "disposition": "shared_keep",
    },
    {"name": "channel", "sf": ["Channel"], "il": ["Channel"], "disposition": "shared_keep"},
    {
        "name": "amortization_type",
        "sf": ["Amortization Type (Formerly Product Type)"],
        "il": ["Amortization Type"],
        "disposition": "shared_keep",
    },
    {
        "name": "property_state",
        "sf": ["Property State"],
        "il": ["Property State"],
        "disposition": "shared_keep",
    },
    {
        "name": "property_valuation_method",
        "sf": ["Property Valuation Method"],
        "il": ["Property Valuation Method"],
        "disposition": "shared_keep",
    },
    {
        "name": "msa",
        "sf": ["Metropolitan Statistical Area (MSA) Or Metropolitan Division"],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "zip3", "sf": ["Postal Code"], "il": [], "disposition": "sf_only"},
    {
        "name": "mi_percent",
        "sf": ["Mortgage Insurance Percentage (MI %)"],
        "il": ["Mortgage Insurance Percent"],
        "disposition": "shared_harmon",
    },
    {
        "name": "mi_cancellation_ind",
        "sf": ["Mortgage Insurance Cancellation Indicator"],
        "il": ["Mortgage Insurance Cancellation Indicator"],
        "disposition": "shared_keep",
    },
    {
        "name": "government_insured_guarantee",
        "sf": [],
        "il": ["Government Insured Guarantee"],
        "disposition": "umbs_only",
    },
    {
        "name": "interest_only_ind",
        "sf": ["Interest Only (I/O) Indicator"],
        "il": ["Interest Only Loan Indicator"],
        "disposition": "shared_keep",
    },
    {
        "name": "io_first_pi_date",
        "sf": [],
        "il": ["Interest Only First Principal and Interest Payment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "months_to_amortization",
        "sf": [],
        "il": ["Months to Amortization"],
        "disposition": "umbs_only",
    },
    {
        "name": "prepayment_penalty_ind",
        "sf": ["Prepayment Penalty Mortgage (PPM) Flag"],
        "il": ["Prepayment Penalty Indicator"],
        "disposition": "shared_keep",
    },
    {
        "name": "prepayment_penalty_term",
        "sf": [],
        "il": ["Prepayment Penalty Total Term"],
        "disposition": "umbs_only",
    },
    {
        "name": "assumability_ind",
        "sf": [],
        "il": ["Assumability Indicator"],
        "disposition": "umbs_only",
    },
    {
        "name": "special_eligibility_program",
        "sf": ["Program Indicator"],
        "il": ["Special Eligibility Program"],
        "disposition": "shared_keep",
    },
    {"name": "arm_index", "sf": [], "il": ["Index"], "disposition": "umbs_only"},
    {"name": "arm_margin", "sf": [], "il": ["Mortgage Margin"], "disposition": "umbs_only"},
    {"name": "arm_pc_margin", "sf": [], "il": ["MBS PC Margin"], "disposition": "umbs_only"},
    {
        "name": "arm_adj_frequency",
        "sf": [],
        "il": ["Interest Rate Adjustment Frequency"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_initial_fixed_period",
        "sf": [],
        "il": ["Initial Fixed Rate Period"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_init_cap_up",
        "sf": [],
        "il": ["Initial Interest Rate Cap Up Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_periodic_cap_up",
        "sf": [],
        "il": ["Periodic Interest Rate Cap Up Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_init_cap_down",
        "sf": [],
        "il": ["Initial Interest Rate Cap Down Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_periodic_cap_down",
        "sf": [],
        "il": ["Periodic Interest Rate Cap Down Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_lookback",
        "sf": [],
        "il": ["Interest Rate Lookback"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_rounding_method",
        "sf": [],
        "il": ["Interest Rate Rounding Method"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_rounding_pct",
        "sf": [],
        "il": ["Interest Rate Rounding Method Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_convertibility",
        "sf": [],
        "il": ["Convertibility Indicator"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_life_ceiling",
        "sf": [],
        "il": ["Life Ceiling Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_life_ceiling_net",
        "sf": [],
        "il": ["Life Ceiling Net Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_life_floor",
        "sf": [],
        "il": ["Life Floor Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "arm_life_floor_net",
        "sf": [],
        "il": ["Life Floor Net Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "borrower_assistance_plan",
        "sf": [],
        "il": ["Borrower Assistance Plan"],
        "disposition": "umbs_only",
    },
    {
        "name": "alternative_delinquency_resolution",
        "sf": [],
        "il": ["Alternative Delinquency Resolution"],
        "disposition": "umbs_only",
    },
    {
        "name": "alternative_delinquency_resolution_count",
        "sf": [],
        "il": ["Number of Alternative Delinquency Resolutions"],
        "disposition": "umbs_only",
    },
    {
        "name": "total_deferral_amount",
        "sf": [],
        "il": ["Total Deferral Amount"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_modification_program",
        "sf": [],
        "il": ["Modification Program"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_modification_type",
        "sf": [],
        "il": ["Modification Type"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_number_of_modifications",
        "sf": [],
        "il": ["Number of Modifications"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_total_capitalized_amount",
        "sf": [],
        "il": ["Total Capitalized Amount"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_original_deferred_amount",
        "sf": [],
        "il": ["Original Deferred Amount"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_current_deferred_upb",
        "sf": [],
        "il": ["Current Deferred UPB"],
        "disposition": "umbs_only",
    },
    {
        "name": "umbs_loan_age_as_of_mod",
        "sf": [],
        "il": ["Loan Age As Of Modification"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_indicator",
        "sf": [],
        "il": ["Interest Rate Step Indicator"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_initial_fixed_period",
        "sf": [],
        "il": ["Initial Step Fixed-Rate Period"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_total_steps",
        "sf": [],
        "il": ["Total Number of Steps"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_remaining_steps",
        "sf": [],
        "il": ["Number of Remaining Steps"],
        "disposition": "umbs_only",
    },
    {"name": "step_next_rate", "sf": [], "il": ["Next Step Rate"], "disposition": "umbs_only"},
    {
        "name": "step_terminal_rate",
        "sf": [],
        "il": ["Terminal Step Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_terminal_date",
        "sf": [],
        "il": ["Terminal Step Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_adj_frequency",
        "sf": [],
        "il": ["Step Rate Adjustment Frequency"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_next_adj_date",
        "sf": [],
        "il": ["Next Step Rate Adjustment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_months_to_next_adj",
        "sf": [],
        "il": ["Months to Next Step Rate Adjustment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "step_periodic_cap_up",
        "sf": [],
        "il": ["Periodic Step Cap Up Percent"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_upb_restated",
        "sf": [],
        "il": ["Origination Mortgage Loan Amount"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_rate_restated",
        "sf": [],
        "il": ["Origination Interest Rate"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_amort_restated",
        "sf": [],
        "il": ["Origination Amortization Type"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_io_restated",
        "sf": [],
        "il": ["Origination Interest Only Loan Indicator"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_fpd_restated",
        "sf": [],
        "il": ["Origination First Payment Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_maturity_restated",
        "sf": [],
        "il": ["Origination Maturity Date"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_term_restated",
        "sf": [],
        "il": ["Origination Loan Term"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_ltv_restated",
        "sf": [],
        "il": ["Origination Loan-To-Value (LTV)"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_cltv_restated",
        "sf": [],
        "il": ["Origination Combined Loan-To-Value (CLTV)"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_dti_restated",
        "sf": [],
        "il": ["Origination Debt-To-Income Ratio"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_credit_score_restated",
        "sf": [],
        "il": ["Origination Credit Score"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_purpose_restated",
        "sf": [],
        "il": ["Origination Loan Purpose"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_occupancy_restated",
        "sf": [],
        "il": ["Origination Occupancy Status"],
        "disposition": "umbs_only",
    },
    {
        "name": "orig_channel_restated",
        "sf": [],
        "il": ["Origination Channel"],
        "disposition": "umbs_only",
    },
    {"name": "delinquency_status", "sf": [], "il": ["Days Delinquent"], "disposition": "umbs_only"},
    {
        "name": "loan_payment_history",
        "sf": [],
        "il": ["Loan Performance History"],
        "disposition": "umbs_only",
    },
    {
        "name": "_filler",
        "sf": [],
        "il": [
            "Filler",
            "Filler_duplicated_0",
            "Filler_duplicated_1",
            "Filler_duplicated_2",
            "Filler_duplicated_3",
            "Filler_duplicated_4",
            "Filler_duplicated_5",
        ],
        "disposition": "drop",
    },
    {
        "name": "super_conforming_ind",
        "sf": ["Super Conforming Flag"],
        "il": [],
        "disposition": "sf_only",
    },
    {
        "name": "preharp_loan_sequence_number",
        "sf": ["Pre-HARP Loan Sequence Number"],
        "il": [],
        "disposition": "sf_only",
    },
    {"name": "harp_ind", "sf": ["HARP Indicator"], "il": [], "disposition": "sf_only"},
]


#: Per-GSE field plans, keyed by agency.
LOAN_ISSUANCE_PLANS: Final[dict[str, list[FieldSpec]]] = {
    "FNMA": FNMA_LOAN_ISSUANCE_PLAN,
    "FHLMC": FHLMC_LOAN_ISSUANCE_PLAN,
}
