"""Import GSE (FNMA and FHLMC) raw data files to bronze layer in parquet format.

This script processes pipe-delimited files with headers from the data/raw
directory and converts them to parquet format in data/bronze, preserving
the GSE and folder structure.

Two import paths live in this module:

1. `run_bronze_import` (and its `PIPE_DELIMITED_WITH_HEADERS` dict)
   — for genuinely pipe-delimited files with header rows. One parquet
   per source zip, schema = the header row.

2. `run_multi_rt_bronze_import` (and its `MULTI_RECORD_TYPE_FILES` dict)
   — for the headerless ISS-family files (`FNM_ISS`, `FNM_RISS`, `FRE_ISS`,
   `FRE_RISS`, `FNM_MS`, `FQ`, `GE`, `MJ`, `XS`, `MZ`). These multiplex
   multiple record types into one file with field 0 as the record-type
   code; field count depends on the record type. Output is hive-partitioned
   per record type: `bronze/{GSE}/{folder}/record_type={rt}/<file>.parquet`.
   See investigations/reports/investigation_iss_schema_recovery_2026-05-24.md.

Excludes from BOTH paths (require bespoke handling):
FNMA:
- SIFMA (fixed-width format)
- REMICSUP (fixed-width format)
- FNM_DEALERREPORT (Excel format)
- RC (fixed-width, 617-char records, no .txt extension)
- FNM_MICA (quarterly reference: two CSVs per zip, uppercase .ZIP)
- NODELAY (formatted plaintext report)
- WLPSEUDO (formatted plaintext report)

FHLMC:
- WR (printable report with page headers, space-aligned columns)
- CFILE (PDF documents)
- FRE_MICA (quarterly reference: two CSVs per zip)
"""

from __future__ import annotations

import tempfile
import zipfile
from pathlib import Path

import polars as pl

from mortgage_data_manager.core.logging import get_logger
from mortgage_data_manager.core.medallion import should_process_file

logger = get_logger(__name__)

# Pinned bronze schemas — auto-generated by `discover_schemas.py`. If the
# module hasn't been generated yet, fall back to an empty mapping; bronze
# import will warn and use polars schema inference as before.
try:
    from mortgage_data_manager.umbs.schemas import BRONZE_SCHEMAS
except ImportError:  # pragma: no cover — generated artefact
    BRONZE_SCHEMAS: dict[str, dict[str, dict[str, pl.DataType]]] = {}


# Headerless multi-record-type files: each line begins with a Record Type code
# (field 0) and the remaining columns depend on the record type. See
# investigations/reports/investigation_iss_schema_recovery_2026-05-24.md
# and the Fannie/Freddie Security Supplemental File specs.
#
# These files are NOT pipe-delimited-with-headers; the existing
# PIPE_DELIMITED_WITH_HEADERS path corrupts them by consuming the first data
# row as headers and silently truncating fields. They must be split per
# record type instead — see `process_zip_to_per_rt_parquet`.
MULTI_RECORD_TYPE_FILES = {
    'FNMA': [
        'FNM_ISS',
        'FNM_RISS',
        'FNM_MS',
        # FNM_ESF_MSS is the Excess-Servicing-Fee Monthly Stratified file —
        # headerless, multi-RT (RTs 1, 3–26 with field counts 12–19 varying by
        # RT). Same structural pattern as FNM_ISS/FNM_MS. Previously misrouted
        # into the headered path, which dropped all RT≥2 rows past field 19.
        'FNM_ESF_MSS',
    ],
    'FHLMC': [
        'FRE_ISS',
        'FRE_RISS',
        'FQ',
        'GE',
        'MJ',
        'XS',
        'MZ',
    ],
}


# Folders whose source files are CSV (comma-delimited with headers) rather than
# the usual pipe-delimited convention. Default separator is '|' for everything
# in PIPE_DELIMITED_WITH_HEADERS.
COMMA_DELIMITED_FOLDERS: dict[str, set[str]] = {
    'FHLMC': {'FRE_Multilender'},
}


def _separator_for(gse: str, folder: str) -> str:
    """Return the field separator for a given (GSE, folder) pair."""
    if folder in COMMA_DELIMITED_FOLDERS.get(gse, set()):
        return ','
    return '|'


# Define which folders contain pipe-delimited files WITH headers
# Maps GSE name -> list of folder names
PIPE_DELIMITED_WITH_HEADERS = {
    'FNMA': [
        'FNM_GN_MEGA',
        'FNM_DPR_FCTR',
        'FNM_ESF_MS',
        'FNM_IS',
        'FNM_RIS',
        'FNM_REMIC',
        'FNM_REMIC_COMPONENT',
        'FNM_REMIC_SHORT',
        'FNM_MF',
        'FNM_ILLD',
        'FNM_MLLD',
        'FNM_RILLD',
        'FNM_SMBS',
        'FNM_RESET_D',
        'FNM_RESET_D_RATES',
        'FNM_RESET_ND',
        'FNM_RESET_ND_RATES',
    ],
    'FHLMC': [
        'FRE_DPR_Fctr',
        'FRE_ILLD',
        'FRE_IS',
        'FRE_Multilender',
        'FRE_RIS',
        'FRE_RILLD',
        # Two-letter codes WITH headers
        'AU',
        'FU',
        'AC',
        'ML',
        'MI',
        'AR',
        'PF',
        'XF',
        'FD',
        'CG',
        'WL',
        'DC',
        'RD',
        'DR',
        'ID',
        'IR',
        'IS',
        'MR',
        'OP',
        'FT',
        'GT',
        'MD',
        'MT',
        'SF',
        'SX',
        'TB',
        'TQ',
        'TV',
        'WJ',
        'MW',
    ]
}


def get_zip_files(raw_dir: Path) -> dict[str, dict[str, list[Path]]]:
    """Get all zip files from the raw data directories.

    Returns a nested dictionary: {GSE: {folder: [zip_files]}}
    """
    zip_files = {}

    for gse, folders in PIPE_DELIMITED_WITH_HEADERS.items():
        gse_dir = raw_dir / gse
        zip_files[gse] = {}

        if not gse_dir.exists():
            logger.warning(f"GSE directory not found: {gse}")
            continue

        for folder in folders:
            folder_path = gse_dir / folder
            if folder_path.exists():
                zips = list(folder_path.glob('*.zip'))
                if zips:
                    zip_files[gse][folder] = zips
                    logger.info(f"Found {len(zips)} zip file(s) in {gse}/{folder}")
                else:
                    logger.warning(f"No zip files found in {gse}/{folder}")
            else:
                logger.warning(f"Folder not found: {gse}/{folder}")

    return zip_files


def process_zip_to_parquet(
    zip_path: Path,
    output_dir: Path,
    overwrite: bool = False,
    *,
    separator: str = '|',
    schema_overrides: dict[str, pl.DataType] | None = None,
) -> bool:
    """Extract a zip file, scan with polars, and sink to parquet.

    Args:
        zip_path: Path to the zip file
        output_dir: Directory where parquet file should be saved
        overwrite: If False, skip files that already exist in bronze
        separator: Field separator for the source file. Defaults to '|' for
            the standard pipe-delimited UMBS feeds; pass ',' for CSV-formatted
            feeds (e.g. FRE_Multilender).
        schema_overrides: Optional per-column dtype map. When provided, the
            CSV is parsed with these dtypes pinned instead of relying on
            polars' first-N-row inference. This is the bug-resistant path
            and the default behavior when called via `run_bronze_import`,
            which looks up the schema from `BRONZE_SCHEMAS`.

    Returns:
        True if successful, False otherwise
    """
    try:
        # Create output directory if it doesn't exist
        output_dir.mkdir(parents=True, exist_ok=True)

        # Get the zip file info
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            file_list = zip_ref.namelist()

            if len(file_list) != 1:
                logger.warning(f"{zip_path.name} contains {len(file_list)} files, expected 1")
                txt_files = [f for f in file_list if f.endswith('.txt')]
                if not txt_files:
                    logger.error(f"No .txt file found in {zip_path.name}")
                    return False
                txt_file = txt_files[0]
            else:
                txt_file = file_list[0]

            # Check uncompressed size
            file_info = zip_ref.getinfo(txt_file)
            size_mb = file_info.file_size / (1024 * 1024)
            logger.info(f"Processing {zip_path.name} -> {txt_file} ({size_mb:.2f} MB uncompressed)")

            if size_mb > 500:
                logger.warning(f"Large file detected: {size_mb:.2f} MB")

            # Extract to temporary directory and process
            with tempfile.TemporaryDirectory() as temp_dir:
                temp_path = Path(temp_dir)
                zip_ref.extract(txt_file, temp_path)
                extracted_file = temp_path / txt_file

                # Create output filename (same as txt file but with .parquet extension)
                output_file = output_dir / Path(txt_file).with_suffix('.parquet').name

                # Check if file exists and skip if overwrite is False
                if not should_process_file(output_file, overwrite):
                    logger.info(f"Skipping {output_file.name} (already exists, use --overwrite to rebuild)")
                    return True

                # Use polars to scan and convert to parquet
                logger.info(f"Scanning {txt_file} with polars...")

                # Scan with the appropriate delimiter. When schema_overrides
                # is supplied, polars uses those dtypes instead of inferring
                # from the first ~100 rows — this prevents the silent-null
                # bug where heterogeneous-prefix files (e.g. FNM_MLLD) had
                # `Security Identifier` inferred as Int64 from numeric-ID
                # rows and then alphanumeric IDs got nulled by `ignore_errors`.
                scan_kwargs = dict(
                    separator=separator,
                    encoding='utf8',
                    has_header=True,
                    ignore_errors=True,
                    truncate_ragged_lines=True,
                )
                if schema_overrides:
                    scan_kwargs['schema_overrides'] = schema_overrides
                df = pl.scan_csv(extracted_file, **scan_kwargs)

                # Sink to parquet
                logger.info(f"Writing to {output_file.relative_to(output_file.parents[2])}")
                df.sink_parquet(output_file, compression='zstd')

                logger.info(f"Successfully processed {zip_path.name}")
                return True

    except Exception as e:
        logger.error(f"Error processing {zip_path.name}: {str(e)}")
        return False


def run_bronze_import(
    raw_dir: Path,
    bronze_dir: Path,
    *,
    overwrite: bool = False,
    gse: str | None = None,
    folders: list[str] | None = None,
) -> dict[str, int]:
    """Import GSE raw zip files to bronze parquet.

    Args:
        raw_dir: Path to the raw data directory.
        bronze_dir: Path to the bronze output directory.
        overwrite: If True, replace existing parquet files.
        gse: Optional GSE filter ('FNMA' or 'FHLMC'). Process both if None.
        folders: Optional list of folder names to process. Process all if None.

    Returns:
        Dict with keys 'processed', 'successful', 'failed'.

    Raises:
        FileNotFoundError: If raw_dir does not exist.
        ValueError: If gse is not None and not 'FNMA' or 'FHLMC'.
    """
    if not raw_dir.exists():
        raise FileNotFoundError(f"Raw directory does not exist: {raw_dir}")

    if gse is not None and gse not in PIPE_DELIMITED_WITH_HEADERS:
        raise ValueError(f"Invalid GSE: {gse!r}. Must be one of {list(PIPE_DELIMITED_WITH_HEADERS)}")

    logger.info("=" * 60)
    logger.info("GSE Data Import: Raw to Bronze (FNMA & FHLMC)")
    logger.info("=" * 60)
    logger.info(f"Raw directory: {raw_dir}")
    logger.info(f"Bronze directory: {bronze_dir}")
    logger.info(f"Overwrite mode: {overwrite}")
    if gse:
        logger.info(f"GSE filter: {gse}")
    if folders:
        logger.info(f"Folder filter: {folders}")
    logger.info("")

    # Create bronze directory
    bronze_dir.mkdir(parents=True, exist_ok=True)

    # Get all zip files
    zip_files = get_zip_files(raw_dir)

    # Apply GSE filter
    if gse is not None:
        zip_files = {k: v for k, v in zip_files.items() if k == gse}

    # Apply folder filter
    if folders is not None:
        folder_set = set(folders)
        zip_files = {
            g: {f: zips for f, zips in gse_folders.items() if f in folder_set}
            for g, gse_folders in zip_files.items()
        }

    if not any(gse_folders for gse_folders in zip_files.values()):
        logger.warning("No zip files found to process")
        return {"processed": 0, "successful": 0, "failed": 0}

    # Process each GSE's folders and zip files
    total_files = sum(
        len(files)
        for gse_folders in zip_files.values()
        for files in gse_folders.values()
    )
    processed = 0
    successful = 0
    failed = 0

    logger.info(f"Found {total_files} total file(s) to process")
    logger.info("")

    for gse_name, gse_folders in zip_files.items():
        if not gse_folders:
            continue

        logger.info(f"Processing GSE: {gse_name}")
        logger.info("=" * 60)

        for folder, zip_list in gse_folders.items():
            logger.info(f"  Folder: {folder}")
            logger.info("  " + "-" * 58)

            # Create corresponding bronze subfolder (preserves GSE structure)
            bronze_subfolder = bronze_dir / gse_name / folder
            sep = _separator_for(gse_name, folder)
            # Look up the pinned column schema for this (GSE, folder). If
            # the folder isn't in BRONZE_SCHEMAS yet (e.g. brand-new feed),
            # we fall back to polars inference with a warning so the import
            # still works but the user knows to regenerate schemas.py.
            schema = BRONZE_SCHEMAS.get(gse_name, {}).get(folder)
            if schema is None:
                logger.warning(
                    f"  {gse_name}/{folder}: no schema in BRONZE_SCHEMAS — "
                    f"falling back to polars inference. Re-run "
                    f"`python -m mortgage_data_manager.umbs.schemas build` "
                    f"to add this folder."
                )

            for zip_path in zip_list:
                processed += 1
                logger.info(f"  [{processed}/{total_files}] {zip_path.name}")

                if process_zip_to_parquet(
                    zip_path, bronze_subfolder, overwrite,
                    separator=sep, schema_overrides=schema,
                ):
                    successful += 1
                else:
                    failed += 1

                logger.info("")

        logger.info("")

    # Summary
    logger.info("=" * 60)
    logger.info("IMPORT SUMMARY")
    logger.info("=" * 60)
    logger.info(f"Total files processed: {processed}")
    logger.info(f"Successful: {successful}")
    logger.info(f"Failed: {failed}")
    if processed > 0:
        logger.info(f"Success rate: {(successful / processed * 100):.1f}%")
    logger.info("")
    logger.info(f"Bronze data location: {bronze_dir}")
    logger.info("=" * 60)

    return {"processed": processed, "successful": successful, "failed": failed}


# ---------------------------------------------------------------------------
# Multi-record-type bronze (headerless ISS-family files)
# ---------------------------------------------------------------------------

def process_zip_to_per_rt_parquet(
    zip_path: Path,
    output_dir: Path,
    *,
    overwrite: bool = False,
) -> dict[str, int]:
    """Split a headerless multi-record-type zip into per-record-type parquets.

    Files like FNM_ISS, FRE_ISS, FNM_MS, etc. are pipe-delimited with no
    header row. Field 0 of each line is a Record Type code (e.g. "1", "2",
    "16"); the remaining field count depends on the record type. This
    function partitions the file by record type and writes one parquet per
    RT under a hive-style directory:

        {output_dir}/record_type={rt}/{txt_basename}.parquet

    All columns are written as String — no semantic schema interpretation
    is applied yet. Column names are dummy placeholders:

        record_type, column_1, column_2, ..., column_N

    Streaming-friendly: uses one cheap Python pre-pass to discover the
    distinct record types and their actual field counts, then one polars
    `scan_csv → filter → sink_parquet` pass per RT so the file never has
    to fit in memory. Peak memory is bounded regardless of file size.

    Args:
        zip_path: Path to the source `.zip` containing one `.txt` file.
        output_dir: Directory under which `record_type={N}/` folders are
            created. Typically `bronze/{GSE}/{folder}/`.
        overwrite: If False, skip RTs whose output parquet already exists.

    Returns:
        Dict mapping `record_type` string → field count for that RT.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path) as zf:
        names = zf.namelist()
        txt_name = next((n for n in names if n.lower().endswith('.txt')), names[0])
        out_basename = Path(txt_name).stem

        # Extract to a temp file so polars can scan it; the zip is small and
        # the extracted .txt may be many GB — polars streams it, so this is fine.
        with tempfile.TemporaryDirectory() as td:
            zf.extract(txt_name, td)
            extracted = Path(td) / txt_name

            # Pre-pass 1 (cheap, Python): discover {rt: max n_fields seen}.
            # Just counts pipes per line; no parsing. ~1M lines/sec on a Mac.
            rt_n_fields: dict[str, int] = {}
            with open(extracted, encoding='utf-8', errors='replace') as fh:
                for line in fh:
                    if not line.strip():
                        continue
                    nf = line.count('|') + 1
                    rt = line.split('|', 1)[0]
                    if nf > rt_n_fields.get(rt, 0):
                        rt_n_fields[rt] = nf

            if not rt_n_fields:
                logger.warning(f"  No data rows found in {zip_path.name}")
                return {}

            max_cols = max(rt_n_fields.values())
            # Pre-pass 2 (streaming, polars): one filter+sink per RT.
            # `schema=` forces N columns regardless of row width; shorter
            # rows get nulls in the trailing positions. Polars streams the
            # file under the hood so memory stays bounded.
            base_schema = {f'_c{i}': pl.String for i in range(max_cols)}

            written: dict[str, int] = {}
            for rt, n_fields in sorted(
                rt_n_fields.items(),
                key=lambda kv: int(kv[0]) if kv[0].isdigit() else 999,
            ):
                rt_dir = output_dir / f"record_type={rt}"
                out_path = rt_dir / f"{out_basename}.parquet"
                if not should_process_file(out_path, overwrite):
                    logger.info(f"  RT={rt:>3}: skipping (exists) {out_path.name}")
                    written[rt] = 0
                    continue
                rt_dir.mkdir(parents=True, exist_ok=True)

                lf = pl.scan_csv(
                    extracted,
                    has_header=False,
                    separator='|',
                    schema=base_schema,
                    truncate_ragged_lines=True,
                    ignore_errors=True,
                )
                # Keep only the first `n_fields` columns for this RT; rename.
                use_cols = [f'_c{i}' for i in range(n_fields)]
                rename_map = {'_c0': 'record_type'}
                for i in range(1, n_fields):
                    rename_map[f'_c{i}'] = f'column_{i}'

                (
                    lf.filter(pl.col('_c0') == rt)
                      .select(use_cols)
                      .rename(rename_map)
                      .sink_parquet(out_path, compression='zstd')
                )
                written[rt] = n_fields
                logger.info(f"  RT={rt:>3}: {n_fields:>2} cols → {out_path.name}")

            return written


def run_multi_rt_bronze_import(
    raw_dir: Path,
    bronze_dir: Path,
    *,
    overwrite: bool = False,
    gse: str | None = None,
    folders: list[str] | None = None,
) -> dict[str, int]:
    """Import headerless multi-record-type GSE files to per-RT bronze parquets.

    Companion to `run_bronze_import` for the headerless ISS-family files
    listed in `MULTI_RECORD_TYPE_FILES`. Splits each zip into one parquet
    per record type under hive-style `record_type={N}/` partitions.

    Args:
        raw_dir: Path to the raw data root.
        bronze_dir: Path to the bronze output root.
        overwrite: If True, replace existing per-RT parquets.
        gse: Optional GSE filter ('FNMA' or 'FHLMC').
        folders: Optional list of folder names to process. Process all if None.

    Returns:
        Dict with keys 'processed', 'successful', 'failed'.

    Raises:
        FileNotFoundError: If raw_dir does not exist.
        ValueError: If `gse` is not None and not in `MULTI_RECORD_TYPE_FILES`.
    """
    if not raw_dir.exists():
        raise FileNotFoundError(f"Raw directory does not exist: {raw_dir}")

    if gse is not None and gse not in MULTI_RECORD_TYPE_FILES:
        raise ValueError(
            f"Invalid GSE: {gse!r}. Must be one of {list(MULTI_RECORD_TYPE_FILES)}"
        )

    logger.info("=" * 60)
    logger.info("GSE Multi-Record-Type Bronze Import (ISS-family)")
    logger.info("=" * 60)
    logger.info(f"Raw directory:    {raw_dir}")
    logger.info(f"Bronze directory: {bronze_dir}")
    logger.info(f"Overwrite mode:   {overwrite}")
    if gse:
        logger.info(f"GSE filter:       {gse}")
    if folders:
        logger.info(f"Folder filter:    {folders}")

    bronze_dir.mkdir(parents=True, exist_ok=True)

    # Discover zip files per GSE/folder
    folder_filter = set(folders) if folders else None
    work: dict[str, dict[str, list[Path]]] = {}
    for g, fldrs in MULTI_RECORD_TYPE_FILES.items():
        if gse and g != gse:
            continue
        g_dir = raw_dir / g
        if not g_dir.exists():
            logger.warning(f"GSE directory not found: {g}")
            continue
        for f in fldrs:
            if folder_filter and f not in folder_filter:
                continue
            fdir = g_dir / f
            if not fdir.exists():
                continue
            zips = sorted(p for p in fdir.glob('*.zip') if '_REV' not in p.name.upper())
            if zips:
                work.setdefault(g, {})[f] = zips

    total = sum(len(z) for gf in work.values() for z in gf.values())
    logger.info(f"Found {total} file(s) to process")
    logger.info("")

    processed = successful = failed = 0
    for g, gse_folders in work.items():
        logger.info(f"Processing GSE: {g}")
        logger.info("=" * 60)
        for folder, zips in gse_folders.items():
            logger.info(f"  Folder: {folder}")
            logger.info("  " + "-" * 58)
            out_root = bronze_dir / g / folder
            for zp in zips:
                processed += 1
                logger.info(f"  [{processed}/{total}] {zp.name}")
                try:
                    process_zip_to_per_rt_parquet(zp, out_root, overwrite=overwrite)
                    successful += 1
                except Exception as exc:
                    failed += 1
                    logger.error(f"  failed: {zp.name} — {exc}")
                logger.info("")

    logger.info("=" * 60)
    logger.info("MULTI-RT IMPORT SUMMARY")
    logger.info("=" * 60)
    logger.info(f"Files processed: {processed}  successful={successful}  failed={failed}")
    logger.info(f"Bronze location: {bronze_dir}")
    logger.info("=" * 60)
    return {"processed": processed, "successful": successful, "failed": failed}


if __name__ == "__main__":
    from mortgage_data_manager.umbs.config import UMBSConfig

    run_bronze_import(
        raw_dir=UMBSConfig.UMBS_RAW_DIR,
        bronze_dir=UMBSConfig.UMBS_BRONZE_DIR,
        overwrite=False,
    )
